# Do not consider loopback addresses as martian source or destination while routing
# Since pods mount the node resolv.conf, they can't use a loopack address that is only
# reachable from the node, so KIND rewrites the well-known docker DNS address 127.0.0.11 
# by a non-loopback address.
# The DNS traffic coming from a pod will have to route to a localhost address to be NATed
# hence we have to enable route_localnet or pods DNS will not work.
net.ipv4.conf.all.route_localnet=1
