name: Build images

on:
  workflow_dispatch:

jobs:
  build-kindnetd:
    name: Kindnet image
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build kindnet image
        run: |
          cd images/kindnetd/
          make
  build-base:
      name: Kindnet image
      runs-on: ubuntu-20.04
      timeout-minutes: 30
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Build base image
          run: |
            cd images/base/
            make


